### ISSUE TITLE
Make the web page responsive

### ISSUE THREAD

**Issue by tusharnankani** [tusharnankani/ToDoList#12]
Current Behaviour: 

![Screenshot (767)](https://user-images.githubusercontent.com/61280281/98971164-d19b2700-2536-11eb-8d48-0fbdab7815dc.png)

![Screenshot (766)](https://user-images.githubusercontent.com/61280281/98971153-cf38cd00-2536-11eb-9500-836c7b78f1fd.png)

**Comment by dr0geo** [comment]
I'd like to work on this one, could you assign me please? :)

**Comment by tusharnankani** [comment]
Great!
Just a reminder, you will have to keep your fork in sync. 
Just read it under [Steps to Follow.](https://github.com/Python-World/python-mini-projects#steps-to-follow)

**Comment by tusharnankani** [comment]
Closed via #14
