### ISSUE TITLE
Add a GitHub Corner or footer

### ISSUE THREAD

**Issue by tusharnankani** [tusharnankani/ToDoList#23]
Add a [Github-Corner](https://github.com/tholman/github-corners) on the **top left corner** or add a footer, which is linked to the repository.

**Comment by SarveshLimaye** [comment]
Hi would like to give a thought about adding github corner on top left corner.

**Comment by tusharnankani** [comment]
Go ahead! @SarveshLimaye

**Comment by tusharnankani** [comment]
Closed #23 via #24.
