### ISSUE TITLE
Add different themes to the website

### ISSUE THREAD

**Issue by tusharnankani** [tusharnankani/ToDoList#5]
The user can choose from different themes.

Something similar to this: [Reference](https://tusharnankani.github.io/AnalogClock/)

**Comment by dr0geo** [comment]
Hey ! I'd like to work on this, could you assign me please ?

**Comment by tusharnankani** [comment]
Hi @dr0geo 

Yes, I will assign it to you. Have you thought of a layout?

**Comment by dr0geo** [comment]
Thank you! 
Yes, I was thinking about using the example you gave in your first comment to place some kind of button in the top right corner to switch from the current dark theme to a light one. Would you rather want to have multiple themes choices, with different main colors?

**Comment by tusharnankani** [comment]
Since the webpage currently has a darker scheme, a light theme is to be implemented. 
- If you are able to manage multiple themes, well and good. 

I was thinking, the current can be the original theme, and 2 more - Light and Darker Themes.
Let me know your thoughts.

**Comment by dr0geo** [comment]
Sounds good to me, I'm working on the light theme at the moment, but I can add another darker one too! 👍🏻

**Comment by tusharnankani** [comment]
Great then, you can work on the light one as of now!
